const $ = (s, root=document) => root.querySelector(s);
const $$ = (s, root=document) => [...root.querySelectorAll(s)];
const state = { me:null, orgId:null, view:'dashboard' };

async function api(path, opts={}) {
  const headers = {'Content-Type':'application/json', ...(opts.headers||{})};
  if (state.orgId) headers['X-Organization-Id'] = state.orgId;
  const res = await fetch(path, {...opts, headers});
  if (res.status === 204) return null;
  const body = await res.json().catch(()=>({}));
  if (!res.ok) throw new Error(body?.error?.message || `HTTP ${res.status}`);
  return body;
}
function money(v){ return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format((Number(v)||0)/100) }
function date(v){ if(!v)return '—'; return new Date(v).toLocaleString('pt-BR') }
function flash(msg,bad=false){ const el=$('#flash'); el.textContent=msg; el.classList.toggle('bad',bad); el.classList.remove('hidden'); setTimeout(()=>el.classList.add('hidden'),5000) }
function node(tag,text,cls){const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(cls)el.className=cls;return el}
function badge(v){ const el=node('span',v||'—','badge '+(v||'')); return el }
function table(rows, columns){ const wrap=node('div',undefined,'table-wrap'); if(!rows?.length){wrap.append(node('div','Nenhum registro.','empty'));return wrap} const t=node('table'),thead=node('thead'),trh=node('tr');columns.forEach(c=>trh.append(node('th',c.label)));thead.append(trh);t.append(thead);const tb=node('tbody');rows.forEach(r=>{const tr=node('tr');columns.forEach(c=>{const td=node('td');const val=c.render?c.render(r):r[c.key];if(val instanceof Node)td.append(val);else td.textContent=val??'—';tr.append(td)});tb.append(tr)});t.append(tb);wrap.append(t);return wrap }
function panel(title, content){const p=node('div',undefined,'panel');const h=node('div',undefined,'panel-head');h.append(node('h2',title));p.append(h);if(content)p.append(content);return p}
function setContent(...els){const c=$('#content');c.replaceChildren(...els)}

async function boot(){ try{ state.me=await api('/console/api/me'); showApp(); }catch{ showLogin(); } }
function showLogin(){ $('#app').classList.add('hidden'); $('#login').classList.remove('hidden') }
function showApp(){ $('#login').classList.add('hidden'); $('#app').classList.remove('hidden'); $('#user-email').textContent=state.me.user.email; $('#admin-nav').classList.toggle('hidden',!state.me.user.platform_admin); const sel=$('#org-select');sel.replaceChildren();state.me.organizations.forEach(o=>{const op=node('option',`${o.name} · ${o.slug}`);op.value=o.id;sel.append(op)});state.orgId=localStorage.getItem('flashpag_org') || state.me.organizations[0]?.id || null;if(state.orgId)sel.value=state.orgId;sel.onchange=()=>{state.orgId=sel.value;localStorage.setItem('flashpag_org',state.orgId);loadView()}; loadView() }

$('#login-form').addEventListener('submit',async e=>{e.preventDefault();$('#login-error').textContent='';try{await api('/console/session',{method:'POST',body:JSON.stringify({email:$('#email').value,password:$('#password').value})});state.me=await api('/console/api/me');showApp()}catch(err){$('#login-error').textContent=err.message}});
$('#logout').onclick=async()=>{await api('/console/session',{method:'DELETE'}).catch(()=>{});state.me=null;showLogin()};
$$('nav button[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;$$('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');loadView()});

const titles={dashboard:['Dashboard','Saldo e atividade recente'],transactions:['Transações','Pix, transferências e saques'],transfers:['Transferências','Enviar Pix e solicitar saque'],customers:['Clientes','Cadastro operacional de pagadores'],integrations:['Integrações','Providers e API keys'],webhooks:['Webhooks','Endpoints de eventos do merchant'],accounts:['Contas','Contas e saldos'],organizations:['Organizações','Estrutura multi-organização'],admin:['Admin','Merchants e provisionamento']};
async function loadView(){const t=titles[state.view]||titles.dashboard;$('#page-title').textContent=t[0];$('#page-subtitle').textContent=t[1];if(!state.orgId && !['organizations','admin'].includes(state.view)){setContent(panel('Sem organização',node('div','Crie uma organização pelo Admin para começar.','empty')));return}try{await ({dashboard,transactions,transfers,customers,integrations,webhooks,accounts,organizations,admin}[state.view]||dashboard)()}catch(err){setContent(panel('Erro',node('div',err.message,'error')))}}

async function dashboard(){const d=await api(`/console/api/summary?organization_id=${encodeURIComponent(state.orgId)}`);const cards=node('div',undefined,'cards');[['Disponível',money(d.balance.available_minor)],['Reservado',money(d.balance.reserved_minor)],['Conta',d.account.name]].forEach(([a,b])=>{const c=node('div',undefined,'card');c.append(node('div',a,'metric-label'),node('div',b,'metric'));cards.append(c)});const recent=table(d.recent_transactions,[{label:'Data',render:r=>date(r.created_at)},{label:'Tipo',key:'kind'},{label:'Status',render:r=>badge(r.status)},{label:'Valor',render:r=>money(r.amount_minor)},{label:'Provider',key:'provider_code'}]);setContent(cards,panel('Últimas transações',recent))}
async function transactions(){const d=await api('/console/api/transactions');setContent(panel('Transações',table(d.data,[{label:'Data',render:r=>date(r.created_at)},{label:'ID',render:r=>{const x=node('span',r.id,'mono');return x}},{label:'Tipo',key:'kind'},{label:'Status',render:r=>badge(r.status)},{label:'Valor',render:r=>money(r.amount_minor)},{label:'Provider',key:'provider_code'}])))}
async function accounts(){const d=await api('/console/api/accounts');const rows=[];for(const a of d.data){let balance='—';try{const s=await api(`/console/api/summary?organization_id=${encodeURIComponent(state.orgId)}`);if(s.account.id===a.id)balance=money(s.balance.available_minor)}catch{}rows.push({...a,balance})}setContent(panel('Contas',table(rows,[{label:'Nome',key:'name'},{label:'Moeda',key:'currency'},{label:'Status',render:r=>badge(r.status)},{label:'Padrão',render:r=>r.is_default?'Sim':'Não'},{label:'Disponível',key:'balance'}])))}
async function customers(){const d=await api('/console/api/customers');const form=document.createElement('form');form.className='form-grid';form.innerHTML=`<label>Nome<input name="name"></label><label>ID externo<input name="external_id"></label><label>E-mail<input name="email" type="email"></label><label>Documento<input name="document"></label><div class="form-actions"><button class="primary" type="submit">Adicionar cliente</button></div>`;form.onsubmit=async e=>{e.preventDefault();const fd=new FormData(form);try{await api('/console/api/customers',{method:'POST',body:JSON.stringify(Object.fromEntries(fd))});flash('Cliente criado');customers()}catch(err){flash(err.message,true)}};setContent(panel('Novo cliente',form),panel('Clientes',table(d.data,[{label:'Nome',key:'name'},{label:'E-mail',key:'email'},{label:'Documento',key:'document'},{label:'ID externo',key:'external_id'},{label:'Criado',render:r=>date(r.created_at)}])))}
async function transfers(){const tx=await api('/console/api/transactions');const form=document.createElement('form');form.className='form-grid';form.innerHTML=`<label>Operação<select name="kind"><option value="transfer">Transferência</option><option value="withdrawal">Saque</option></select></label><label>Provider<select name="provider">${state.me.installed_providers.map(p=>`<option>${p}</option>`).join('')}</select></label><label>Valor em centavos<input name="amount_minor" type="number" min="1" required></label><label>Chave Pix<input name="pix_key" required></label><label class="wide">Descrição<input name="description"></label><div class="form-actions"><button class="primary" type="submit">Enviar</button></div>`;form.onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(form));data.amount_minor=Number(data.amount_minor);const kind=data.kind;delete data.kind;try{await api(`/console/api/${kind==='withdrawal'?'withdrawals':'transfers'}`,{method:'POST',body:JSON.stringify(data)});flash(kind==='withdrawal'?'Saque solicitado':'Transferência criada');transfers()}catch(err){flash(err.message,true)}};const rows=tx.data.filter(r=>r.kind==='transfer'||r.kind==='withdrawal');setContent(panel('Nova saída Pix',form),panel('Histórico',table(rows,[{label:'Data',render:r=>date(r.created_at)},{label:'Tipo',key:'kind'},{label:'Status',render:r=>badge(r.status)},{label:'Valor',render:r=>money(r.amount_minor)},{label:'Chave',key:'pix_key'}])))}
async function integrations(){const [conns,keys]=await Promise.all([api('/console/api/provider-connections'),api('/console/api/api-keys')]);const wrap=node('div',undefined,'split');const pf=document.createElement('form');pf.className='form-grid';pf.innerHTML=`<label>Provider<select name="provider">${state.me.installed_providers.map(p=>`<option>${p}</option>`).join('')}</select></label><label>Nome<input name="label" value="default"></label><label class="wide">Credenciais JSON<textarea name="credentials" rows="5" placeholder='{"webhook_secret":"..."}'></textarea></label><div class="form-actions"><button class="primary">Conectar provider</button></div>`;pf.onsubmit=async e=>{e.preventDefault();const f=new FormData(pf);let credentials={};try{credentials=f.get('credentials')?JSON.parse(f.get('credentials')):{}}catch{return flash('JSON de credenciais inválido',true)}try{await api('/console/api/provider-connections',{method:'POST',body:JSON.stringify({provider:f.get('provider'),label:f.get('label'),credentials})});flash('Provider conectado');integrations()}catch(err){flash(err.message,true)}};wrap.append(panel('Nova conexão',pf));const kf=document.createElement('form');kf.className='form-grid';kf.innerHTML=`<label class="wide">Nome da API key<input name="name" value="default"></label><div class="form-actions"><button class="primary">Criar API key</button></div><div id="created-key" class="wide"></div>`;kf.onsubmit=async e=>{e.preventDefault();try{const out=await api('/console/api/api-keys',{method:'POST',body:JSON.stringify({name:new FormData(kf).get('name')})});const box=$('#created-key',kf);box.textContent=out.secret;box.className='secret wide';flash('API key criada. Copie agora; ela não será exibida novamente.')}catch(err){flash(err.message,true)}};wrap.append(panel('Nova API key',kf));setContent(wrap,panel('Providers',table(conns.data,[{label:'Provider',key:'provider_code'},{label:'Nome',key:'label'},{label:'Status',render:r=>badge(r.status)},{label:'Criado',render:r=>date(r.created_at)},{label:'Teste',render:r=>{const b=node('button','Testar','primary');b.type='button';b.onclick=async()=>{b.disabled=true;try{const h=await api(`/console/api/provider-connections/${r.id}/test`,{method:'POST'});flash(h.healthy?`${r.provider_code} conectado · disponível ${money(h.available_minor)}`:`${r.provider_code} indisponível`,!h.healthy)}catch(err){flash(err.message,true)}finally{b.disabled=false}};return b}}])),panel('API keys',table(keys.data,[{label:'Nome',key:'name'},{label:'Prefixo',render:r=>node('span',r.prefix,'mono')},{label:'Scopes',render:r=>(r.scopes||[]).join(', ')},{label:'Último uso',render:r=>date(r.last_used_at)}])))}
async function webhooks(){const d=await api('/console/api/webhook-endpoints');const f=document.createElement('form');f.className='form-grid';f.innerHTML=`<label class="wide">URL HTTPS<input name="url" type="url" required placeholder="https://seu-sistema.com/webhooks/flashpag"></label><label class="wide">Descrição<input name="description"></label><div class="form-actions"><button class="primary">Adicionar endpoint</button></div><div id="webhook-secret" class="wide"></div>`;f.onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(f));try{const out=await api('/console/api/webhook-endpoints',{method:'POST',body:JSON.stringify(data)});const box=$('#webhook-secret',f);box.textContent=out.secret;box.className='secret wide';flash('Webhook criado. Guarde o secret de assinatura.');webhooks()}catch(err){flash(err.message,true)}};setContent(panel('Novo webhook',f),panel('Endpoints',table(d.data,[{label:'URL',key:'url'},{label:'Eventos',render:r=>(r.events||[]).join(', ')},{label:'Status',render:r=>badge(r.status)},{label:'Criado',render:r=>date(r.created_at)}])))}
async function organizations(){const rows=state.me.organizations;setContent(panel('Organizações disponíveis',table(rows,[{label:'Nome',key:'name'},{label:'Slug',key:'slug'},{label:'Merchant',render:r=>node('span',r.merchant_id,'mono')},{label:'Status',render:r=>badge(r.status)}])))}
async function admin(){if(!state.me.user.platform_admin){setContent(panel('Acesso negado',node('div','Você não é platform admin.','empty')));return}const wrap=node('div',undefined,'split');const mf=document.createElement('form');mf.className='form-grid';mf.innerHTML=`<label class="wide">Merchant<input name="name" required></label><label class="wide">Owner user UUID (opcional)<input name="owner_user_id"></label><div class="form-actions"><button class="primary">Criar merchant</button></div>`;mf.onsubmit=async e=>{e.preventDefault();try{await api('/console/api/admin/merchants',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(mf)))});flash('Merchant criado');await refreshMe();admin()}catch(err){flash(err.message,true)}};wrap.append(panel('Novo merchant',mf));const of=document.createElement('form');of.className='form-grid';of.innerHTML=`<label>Merchant<select name="merchant_id">${state.me.merchants.map(m=>`<option value="${m.id}">${m.name}</option>`).join('')}</select></label><label>Nome<input name="name" required></label><label class="wide">Slug<input name="slug" required></label><div class="form-actions"><button class="primary">Criar organização + conta</button></div>`;of.onsubmit=async e=>{e.preventDefault();try{await api('/console/api/admin/organizations',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(of)))});flash('Organização criada');await refreshMe();admin()}catch(err){flash(err.message,true)}};wrap.append(panel('Nova organização',of));setContent(wrap,panel('Merchants',table(state.me.merchants,[{label:'Nome',key:'name'},{label:'ID',render:r=>node('span',r.id,'mono')},{label:'Status',render:r=>badge(r.status)}])))}
async function refreshMe(){state.me=await api('/console/api/me');showApp()}

boot();
